[project]
name = "mypkg"
version = "0.1.0"
description = ""
requires-python = ">=3.12.6"
dependencies = []

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[dependency-groups]
dev = [
    "loguru>=0.7.3",
]
